social:
  fa-brands fa-github-alt: https://github.com/rimdl || Github || "#hdhfbb"
  fa-solid fa-envelope: mailto:renjie.air@outlook.com || email || "#feca57"

# A simple 404 page
error_404:
  enable: true
  subtitle: "页面没有找到"
  background: /images/404.svg

favicon: /images/favicon.ico

nav:
  logo: /images/avatar.png
#  logo: "./source/images/avatar.png"
  display_title: true
  fixed: false # fixed navigation bar

menu:
  首页: /
  时间轴: /archives/
  标签: /tags/
  分类: /categories/
  各种链接: /links/
#  关于: /about/

avatar:
  img: /images/avatar.png
  effect: false # true头像会一直转圈

index_img:
archive_img: /images/bg2.svg
tag_img: /images/bg2.svg
category_img: /images/bg2.svg

cover:
  # 是否显示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面显示的位置
  # 三个值可配置 left , right , both
  position: left
  # 当没有设置cover时，默认的封面显示
  default_cover: /images/cool-background.svg

post_meta:
  page:
    date_type: both # created or updated or both 主页文章日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标签
    label: true # true or false 显示描述性文字
  post:
    date_type: both # created or updated or both 文章页日期是创建日或者更新日或都显示
    date_format: relative # date/relative 显示日期还是相对日期
    categories: true # true or false 文章页是否显示分类
    tags: true # true or false 文章页是否显示标签
    label: true # true or false 显示描述性文字

post_copyright:
  enable: true
  decode: false
  author_href: https://blog.xinsi.space/
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

reward:
  enable: true
  text:
  QR_code:
    - img: /images/reward_wx.png
      link:
      text: 微信

toc:
  post: true
  page: true
  number: true
  expand: false
  style_simple: false # for post
  scroll_percent: true

related_post:
  enable: true
  limit: 6 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

# Displays outdated notice for a post (文章过期提醒)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 30 # When will it be shown
  position: top # position: top/bottom
  message_prev: 本文写作（更新）于
  message_next: 天前，内容可能已过时，请注意辨别。

post_pagination: 1

footer:
  owner:
    enable: true
    since: 2023
  custom_text: Hi, 欢迎访问我的 <a href="https://blog.xinsi.space/">blog</a>!

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: 我的github
      link: https://github.com/rimdl
  card_announcement:
    enable: true
    content: <h3 style="color:black">我的blog上线了！</h3><h5>扫描B站或抖音二维码关注，与我交流~</h5><img src="https://raw.gitmirror.com/rimdl/pic/master/bilibili.png" style="width:100%;border-radius:20px"><br><img src="https://raw.gitmirror.com/rimdl/pic/master/douyin.png" style="width:100%;border-radius:20px">
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
    orderby: random # Order of tags, random/name/length
    order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works
  card_post_series:
    enable: true
    orderBy: 'date' # Order by title or date
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
  # Aside widget - Newest Comments
  newest_comments:
    enable: true
    sort_order: # Don't modify the setting unless you know how it works
    limit: 6
    storage: 10 # unit: mins, save data to localStorage
    avatar: true

# Local search
local_search:
  enable: true
  # Preload the search data when the page loads.
  preload: true
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  CDN:

sharejs:
  enable: true
  sites: wechat,weibo,qq  #想要显示的内容

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo
  use: giscus
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in top_img
  card_post_count: false # Display comment count in Home Page
  # Giscus
  # https://giscus.app/
giscus:
  repo: xinsi-tecool/blogcomments
  repo_id: R_kgDOLERiAw
  category_id: DIC_kwDOLERiA84CcY-p
  theme:
    light: light
    dark: dark
  option:

cloudflare_analytics: ee55eb6fd7f145359e4c4269d9553077

theme_color:
  enable: true
  main: "#81ecec"
  paginator: "#74b9ff"
  button_hover: "#74b9ff"
  text_selection: "#7ed6df"
  link_color: "#4edec7"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#4edec7"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#48dbfb"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"
  scrollbar_color: "#49b1f5"

background: "rgba(27, 31, 35, .05)"

footer_bg: false

canvas_fluttering_ribbon:
  enable: false
  mobile: false # false 手机端不显示 true 手机端显示

# 主页subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  # loop (循环打字)
  loop: false
  # source 调用第三方服务
  # source: false 关闭调用
  # source: 1  调用一言网的一句话（简体） https://hitokoto.cn/
  # source: 2  调用一句网（简体） http://yijuzhan.com/
  # source: 3  调用今日诗词（简体） https://www.jinrishici.com/
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: 2
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字

# 加载动画 Loading Animation
preloader:
  enable: false
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 1
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url:

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

fancybox: true

# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: true

instantpage: true

inject:
  head:
    - <link rel="stylesheet" href="/css/butterfly.css">



